module LoCal

public export
data Ty : Type where
  T0      : Ty
  Pair    : Ty -> Ty -> Ty   -- serial access only, fst then snd
  Either  : Ty -> Ty -> Ty
  I64     : Ty
  -- IDEA: Offset - region local ; Ptr - cross region
  Offset  : Ty -> Ty -- signed pointer offset value
  Ptr     : Ty -> Ty -- raw pointer ; no tag ; just the location data
  -- recursive type support
  Box     : Lazy Ty -> Ty

public export
getStaticSize : Ty -> Maybe Int
getStaticSize = \case
  T0    => Just 0
  I64   => pure 8
  Offset _ => pure 8
  Ptr _ => pure 8
  Pair a b => do
    sa <- getStaticSize a
    sb <- getStaticSize b
    pure (sa + sb)
  Either a b => do
    sa <- getStaticSize a
    sb <- getStaticSize b
    if sa == sb -- special case, when the left and right size matches and statically known
      then Just (1 + sa)
      else Nothing
  Box _ => Nothing

{-
  INSIGHT:
    control flow construct data
      if          -> + types
      basic block -> * types
    unconstrained recursion needs Box!!!
-}

{-
  REPRESENTATION:
    - no tag:   I64, Pair
    - has tag:  Either

  FUTURE WORK:
    - either should use only one bit tag
      + implement packing of multiple tags into a byte or multiple bytes
      + implement sub byte/word addressing but by tags and data
    - add alignment control to locations
-}


public export
data Region : Type where
  MkRegion : Int -> Region

public export
data Loc : (r : Region) -> Type where
  LocStart    : (t : Ty) -> (r : Region) -> Loc r
  LocAfter    : (t : Ty) -> Loc r -> Loc r   -- Q: dynamically/runtime known? maybe a better name is RuntimeAfter ; A: NO!
                -- INSIGHT: if we would put Ty to this (instead of static size that would provide enough information to generate runtime function to calculate an endwitness
                -- IDEA: location is not the right thing that descibes the next location
                --        instead it would be the end witness of some value!
                --        location + size-witness = end-witness
          --    ^ this should be a value variable instead of Ty, that would solve the sizeof problem with either's left/right
          --    Q: what problem would it cause?
          -- TODO: LocAfter should get a proof that an end-witness is existing for prev loc
          --        maybe EndWitness should be indexed with Loc then it would be the proof
  LocAfterTag : String -> (t : Ty) -> Loc r -> Loc r         -- statically known ; used for jump over the tag

{-
  Q:
    do we need locations for building only?
    do we need locations for deconstruction?

  - locations can be queried from variables
-}

{-
  mvp simplifications:
    - only pair and either ; product and sum type
    - only I64 interger primitive type
    - functions with only single argument
    - no sharing

  Q: what about stack frames and stack based memory management?
  Q: what about returning values in registers?
  A: use special region for that, or use escape analysis on regions

  mvp example:
    - program read user input N:int
    - creates a List of Int from 1 to N unpacked in a buffer

-}

{-
  currently sharing is not supported
  for support we need:
    + indirection value
    + location for indirection
    + linear value types ; in Let
    + dup hoas primitive

  IDEA:
    locations are linear, values are not ; INSIGHT: locations are identifiers for values, so values are linear also
    sharing could be supported by recognizing non linear value usage
    for duplicates instead of the value an indirection is written
-}

{-
  sharing support:
    - explicit indirections, linear locations, DUP for locations to model indirection
    - implicit sharing: use coercions for automatic DUP insertion
-}

public export
data EndWitness = NoEW | EW -- TODO: index it with Loc

-- TODO: add linear arrows to guarantee that codegen happens for each expression exactly once
{-
  Q: is LoCal program pure and can it be interpreted through data dependencies only where dependecy is sequential due to neighboring locations?
     does the Exp's operations guarantee dependency serializability through the EW type constraints?

  TODO:
    - new backend for the CPS IR:
      + operations are generated by following theit locations from start to the end
      + each region is filled sequentially, but region's operation codegen can be interleaved
      why? because for the non CPS IR the codegen naturally followed the location order,
        i.e. for Tup2 first generated code for fst then for snd and Tup2 codegen happended strictly before fst and snd codegen, and that is not true for CPS
        see the following example where snd's MkI64 expression is the root where the codegen start:
            MkI64 102 $ \snd =>
            MkI64 101 $ \fst =>
            MkRTup2 fst snd $ \fst, snd, t => t

      Q: why is CPS good then?
      A: because: a) it avoids explosion b) traversal effect is tracked

      INSIGHT: the direct value style IR express location order directed codegen naturally, so it is better than the CPS IR version
-}

public export
data IntOp2 = Plus | Sub | Times | Quot | Rem

public export
data CmpOp = EQ | GE | GT | LE | LT | NE

public export
data Exp : (t : Ty) -> (loc : Loc r) -> (ew : EndWitness) -> (saved_ews : List Type) -> Type

public export
data Arg : (sig : List Type) -> Type where
  Arg0 : Arg []
  ArgN : {t : _} -> {r : _} -> {loc : Loc r} -> {ew : _} -> Exp t loc ew [] -> Arg s -> Arg (Exp t loc ew [] :: s)

data Exp where

  -- Q: when to introduce new regions? A: for intermediate values
  LetRegion : (Region -> Exp t loc ew ews) -> Exp t loc ew ews
  LetRegionValue : {t_val : _} -> (r_val : Region) -> Exp t_val (LocStart t_val r_val) EW [] -> (Exp t_val (LocStart t_val r_val) EW [] -> Exp a loc ew ews) -> Exp a loc ew ews

  MkStaticEW : {ew_in : _} -> {auto _ : Just size = getStaticSize t} -> Exp t loc ew_in [] -> Exp t loc EW []

  -- to copy values cross region ; requires full traversal effect on the argument, so the end-witness should be available
  Copy : {loc_in : _} -> Exp t loc_in EW [] -> Exp t loc EW []

  -- boxing
  MkBox : Exp t loc ew [] -> Exp (Box t) loc ew []
  UnBox : Exp (Box t) loc ew [] -> Exp t loc ew []


  -- value shapes, ADT can be modeled with these
  {-
    MkPair is the only place that introduces after relation between locations
    IDEA:
      - instead of LocAfter Ty we should use size which should be included in the Exp
      - the Exp size could be used to define the region size also
  -}

  MkPair : {a, b : Ty} -> {loc : _} -> {ew : _} ->
    let locFst = LocAfterTag "Pair" a loc in
    let locSnd = LocAfter b locFst in
    Exp a locFst EW [] -> Exp b locSnd ew [] -> Exp (Pair a b) loc ew []

  MkLeft  : {a, b : Ty} -> {loc : _} -> {ew : _} ->
    let locArg = LocAfterTag "Left" a loc in
    Exp a locArg ew [] -> Exp (Either a b) loc ew []

  MkRight : {a, b : Ty} -> {loc : _} -> {ew : _} ->
    let locArg = LocAfterTag "Right" b loc in
    Exp b locArg ew [] -> Exp (Either a b) loc ew []

{-
  TODO:
    every data access needs to be tested to Ind and do the dereference for it
    INSIGHT: sharing poisons code, because requires interpretation
-}
  -- RTup2 a b   = Pair (Offset b) (Pair a b)
  -- RTup3 a b c = Pair (Offset b) (Pair (Offset c) (Pair a (Pair b c)))
  -- RTup3 a b c = Offset b # Offset c # a # b # c

  -- serial access pair
  CasePair : {r_tup : _} -> {a, b, c : Ty} -> {loc_tup : Loc r_tup} -> {ew_tup, ew : _} -> {loc : _} -> {ews : _} ->
              Exp (Pair a b) loc_tup ew_tup [] ->
              let locFst = LocAfterTag "Pair" a loc_tup in
              let locSnd = LocAfter b locFst in
              ( Exp a locFst NoEW [] ->
                -- gives access for snd
                (snd_fun : Exp a locFst EW [] -> Exp b locSnd ew_tup []) ->
                -- gives end-witness for Pair
                {tup_ew_fun : Exp b locSnd EW [] -> Exp (Pair a b) loc_tup EW []} ->
                Exp c loc ew ews
              ) -> Exp c loc ew ews

{-
  IDEA:
    - model cursors and end witnesses
    - sizeof handling
      + can generate end-witness at compile time from Ty                        ; compile time = end-witness value
      + can genetrate end-witness producing runtime function at compile time    ; runtime      = end-witness function : value -> end-witness
-}
  CaseEither : {r_scrut : _} -> {a, b, c : Ty} -> {loc_scrut : Loc r_scrut} -> {ew_scrut, ew : _} -> {loc : _} -> {ews : _} ->
               Exp (Either a b) loc_scrut ew_scrut [] ->
               let locL = LocAfterTag "Left"  a loc_scrut in
               let locR = LocAfterTag "Right" b loc_scrut in
               (Exp a locL ew_scrut [] -> {either_ew_fun : Exp a locL EW [] -> Exp (Either a b) loc_scrut EW []} -> Exp c loc ew ews) ->
               (Exp b locR ew_scrut [] -> {either_ew_fun : Exp b locR EW [] -> Exp (Either a b) loc_scrut EW []} -> Exp c loc ew ews) ->
               Exp c loc ew ews
               -- PROBLEM/TODO: what if the output size differs?
               -- A: there is no problem because the location would be the same and the end witness will be different
               -- IDEAS: is the result size an Either Int Int?

  -- fun app ; needs more work to return end-witnesses
  -- IDEA: store end-witnesses as an index in Exp

  AddEW : Exp t1 loc1 EW [] -> Exp t2 loc2 ew2 ews2 -> Exp t2 loc2 ew2 (Exp t1 loc1 EW [] :: ews2)

  FunAppNew : {res : _} -> {r_res : _} -> {loc_res : Loc r_res} ->
           String ->
           (fun_def : Arg exps_in -> Exp res loc_res EW fun_ews) ->
           (fun_args : Arg exps_in) ->
           (Arg fun_ews -> Exp res loc_res EW [] -> Exp c loc ew ews) ->
           Exp c loc ew ews
  {-
  FunApp2 : {r_arg, r_res : _} -> {t_arg, res : _} -> {loc_arg : Loc r_arg} -> {loc_res : Loc r_res} -> {ew_arg : _} ->
           String ->
           --(fun_def : Exp t_arg loc_arg ew_arg -> (Exp t_arg loc_arg ew_arg_out, Exp res loc_res EW)) ->
           (fun_def : Exp t_arg loc_arg NoEW -> Exp res loc_res EW) ->
           Exp t_arg loc_arg ew_arg ->
           --(Exp t_arg loc_arg ew_arg_out -> Exp res loc_res EW -> Exp c loc ew) ->
           Exp res loc_res EW
  -}
  -- indirection, within same region
  MkOffset    : {ew_in : _} -> {r : _} -> {loc, loc_in : Loc r} -> Exp x loc_in ew_in [] -> Exp (Offset x) loc EW []
  DeRefOffset : {x : _} -> {ew_in : _} -> {r_in : _} -> {loc_in : Loc r_in} ->
                Exp (Offset x) loc_in ew_in [] -> ({r_val : _} -> Exp x (LocStart x r_val) NoEW [] -> Exp a loc ew ews) -> Exp a loc ew ews

  {-
    TODO:
      - add assertion to throw error on read before write situations, which can happen with forward pointers and dereference
      - create and example for this case
      Q: how does this interact with function calls?
  -}
  -- indirection, cross region
  MkPtr    : {ew_in : _} -> {r_in : _} -> {loc_in : Loc r_in} -> Exp x loc_in ew_in [] -> Exp (Ptr x) loc EW []
  DeRefPtr : {x : _} -> {ew_in : _} -> {r_in : _} -> {loc_in : Loc r_in} ->
             Exp (Ptr x) loc_in ew_in [] -> ({r_val : _} -> Exp x (LocStart x r_val) NoEW [] -> Exp a loc ew ews) -> Exp a loc ew ews

  -- primitive values
  MkT0  : Exp T0 loc EW []
  MkI64 : Int -> Exp I64 loc EW []

  -- I64 primops
  I64Op2  : IntOp2 -> {ew1, ew2 : _} -> {loc_in1, loc_in2 : _} -> Exp I64 loc_in1 ew1 [] -> Exp I64 loc_in2 ew2 [] -> Exp I64 loc EW []
  I64Cmp  : CmpOp  -> {ew1, ew2 : _} -> {loc_in1, loc_in2 : _} -> Exp I64 loc_in1 ew1 [] -> Exp I64 loc_in2 ew2 [] -> Exp (Either T0 T0) loc EW []

  I64Op2CE : IntOp2 -> Int -> {ew2 : _} -> {loc_in2 : _} -> Exp I64 loc_in2 ew2 [] -> Exp I64 loc EW []
  I64Op2EC : IntOp2 -> {ew1 : _} -> {loc_in1 : _} -> Exp I64 loc_in1 ew1 [] -> Int -> Exp I64 loc EW []
  I64CmpC  : CmpOp  -> Int -> {ew2 : _} -> {loc_in2 : _} -> Exp I64 loc_in2 ew2 [] -> Exp (Either T0 T0) loc EW []

  -- IO primops
  PrintI64 : {ew_in : _} -> {loc_in : _} -> Exp I64 loc_in ew_in [] -> (() -> Exp t loc ew ews) -> Exp t loc ew ews

  -- prints the buffer content at the location in hexadecimal ; requires full traversal effect on the argument, so the end-witness should be available
  PrintValue : {loc_in : _} -> Exp t_in loc_in EW [] -> (() -> Exp t loc ew ews) -> Exp t loc ew ews

  -- internal
  Var : Exp t loc ew sew

  InheritEW : {r_in : _} -> {loc_in : Loc r_in} -> Exp a loc_in EW [] -> Exp b loc EW []

  AddLocAfter : {b : _} -> {locFst : _} -> Exp a locFst EW [] -> Exp b (LocAfter b locFst) ew []


public export
data Program : Type where
  Main  : {res : Ty} -> Exp res (LocStart res (MkRegion (-1))) EW [] -> Program

--export infixr 5 #
export infixr 5 ##

%inline
(#) : Ty -> Ty -> Ty
(#) a b = Pair a b

%inline
(##) : {a, b : Ty} -> {loc : _} -> {ew : _} ->
    let locFst = LocAfterTag "Pair" a loc in
    let locSnd = LocAfter b locFst in
    Exp a locFst EW [] -> Exp b locSnd ew [] -> Exp (Pair a b) loc ew []

(##) = MkPair

{-
sample_tup2_01 : {r : _} -> {loc : Loc r} -> Exp (Offset I64 # I64 # I64) loc EW
sample_tup2_01 = let a = MkI64' 102 in MkOffset a ## MkI64 12 ## MkI64 103

sample_tup2_02 : {r : _} -> {loc : Loc r} -> Exp (I64 # Offset I64 # I64 # I64) loc EW
sample_tup2_02 = let a = MkI64 102 in a ## MkOffset a ## a ## MkI64 103
-}

-- TODO: codegen this
sample_tup2_03 : {r : _} -> {loc : Loc r} -> Exp (I64 # Offset I64 # I64 # I64) loc EW []
sample_tup2_03 = let a = MkI64 102 in MkPair (Copy a) $ MkPair (MkOffset a) $ MkPair ( a) $ MkI64 103
{-
sample_tup2_03_err : {r : _} -> {loc : Loc r} -> Exp (I64 # Offset I64 # I64 # I64) loc EW
sample_tup2_03_err = let a = MkI64 102 in MkPair a $ MkPair (MkOffset a) $ MkPair a $ MkI64 103
-}
sample_a : {r : _} -> {loc : Loc r} -> Exp I64 loc EW []
sample_a = MkI64 102

{-
sample_tup2_03_err : {r : _} -> {loc : Loc r} -> Exp (I64 # I64) loc EW
sample_tup2_03_err = let a = MkI64 102 in MkPair a a
-}

sample_tup2_04 : {r : _} -> {loc : Loc r} -> Exp (I64 # I64) loc EW []
sample_tup2_04 = MkPair sample_a sample_a

My_ty3 : Ty
My_ty3 = Ptr $ Box My_ty3

sample_box_ptr : {r : _} -> {loc : Loc r} -> Exp My_ty3 loc EW []
sample_box_ptr = MkPtr {loc_in=loc} $ MkBox sample_box_ptr

public export
AddI64 : {ew1, ew2 : _} -> {loc_in1, loc_in2 : _} -> Exp I64 loc_in1 ew1 [] -> Exp I64 loc_in2 ew2 [] -> Exp I64 loc EW []
AddI64 = I64Op2 Plus

public export
EqI64 : {ew1, ew2 : _} -> {loc_in1, loc_in2 : _} -> Exp I64 loc_in1 ew1 [] -> Exp I64 loc_in2 ew2 [] -> Exp (Either T0 T0) loc EW []
EqI64 = I64Cmp EQ

public export
AddI64C : Int -> {ew1 : _} -> {loc_in1 : _} -> Exp I64 loc_in1 ew1 [] -> Exp I64 loc EW []
AddI64C = I64Op2CE Plus

public export
EqI64C, LtI64C : Int -> {ew1 : _} -> {loc_in1 : _} -> Exp I64 loc_in1 ew1 [] -> Exp (Either T0 T0) loc EW []
EqI64C = I64CmpC EQ
LtI64C = I64CmpC LT

-- -------------------------------

{-
  TODO:
    SKIP - write buffer based interpreter
    done - write C backend
    done - write example for function call
  Q: should we distinguish register and memory values ; ref or immediate value?
-}

{-
  Q: how to express location relations?
    a) flattened low level: sequence of prim types            ; locations are sequenced linearly           (list of locations) ; compatible with linear types
    b) high level:          sequence of high level structures ; locations can be referenced multiple times (tree of locations) ; needs multi modality

  NOTE:
    the problem of the list of locations approach is that it fixes the layout and we want to support filed reordering, so the location language must support that


  PROBLEM:
    currently a tup2 I64 I64 representation can be arbitraty, but it will be written correctly due to locations,
      but the consumer (reader) side might use a different layout,
      for example the producer side could use a [TAG, trash, fst I64, trash, snd I64] layout
      and the consumer side just would expect a packed [TAG, fst I64, snd I64] layout,
      which would not work
    to solve it the type and layout must be attached
    Q: where to attach?
      a) Ty
      b) Exp  ; <=== I'd prefer this

    Q: what would be the layout language?

  LAYOUT MVP:
    - force to use packed ; left to right layout ordering
    - make it correct by construction
-}



-- -------------------------------

{-
  ingredients
    App - function + one argument
    Tup2
    Either
    Top level functions:
      def + arr
    fst, snd
    either - control flow based eliminator
-}

{-
  NOTES:
    location is: staticly known or dynamicly/runtime known
-}

{-
  put either and tup2 and I64 into buffers
-}

{-
  IDEA:
    hybrid elaborator:
      + edsl with type guarantees derived from meta language
        example: usual functional language (L1 gibbon)
      + edsl hoas interpreter that infers dsl types further
        example: functional language with locations (L2 gibbon)
                 the interpreter would insert locations
                 the LoCal is a correct by construction language for locations, the interpreter would build it
-}

{-
  TODO:
    - create high level simple functional hoas edsl
    - create interpreter that compiles the high level hoas edsl to LoCal edsl, with inferring and inserting locations
-}

{-
  INSIGHT:
  - the interpreter might rely on a less typed IR for input, i.e. when linearity would be broken due to interpretation requirements
  - locations might be pre interpreted before value allocations, so that the addresses would be already available
-}

{-
  INSIGHT:
  - location is the descriptor where to find the data
    + if it is static then to can turn to code
    + if it is dynamic then it needs runtime interpretation

  Q: is this a valid example?
      create a value: Tup2 [garbage] fst snd
      pass to a function to return the snd
      Q: can the callee skip the [garbage]?
      A: YES, if the input location is passed statically or dynamically

  Q: can the target language implemented as a fully dynamic system that works with dynamic locations and buffers,
     and with staging we could specialize the static parts of the programs?
     would this be the same system as gibbon/LoCal?


  IDEA/EXPERIMENT:
    create a high level functional language that works without locations but runs on serialized representation,
    where all locations are handled dynamically in an interpreter

    INSIGHT:
      the source code statically defines the constructed values and their positions, but in not serialized way,
      but when the locations are derived only from source code then they are static also, because the source code is static


  METHOD:
    high level language (simple functional language)
    interpreted on the target system's architecture (buffer based system)
    everything is runtime
    OUTCOME:
      structured implementation
      with staging the static parts we can get a compiler and an efficient but generic solution

    Q: what if we use the LoCal language as an input and for interpretation?
    INSIGHT: LoCal = high level language + locations

    Q: what about interleaved garbage in the result data?
    TODO:
      - create a gibbon example for this, check the C code ; see: WritePackedFile
        gibbon allocates garbage into a separate region, and it puts the output into the same region
      - how will my interpreter handle this?
  TODO:
    done - add Ind eliminator: DeRefPtr
    Q: when a pointer is a forward reference then is it possile that it will be dereferred before it is written?
    A: yes, which is wrong.
      Q: how to avoid this situation? is it possible to track effects in types?


  TODO:
    done - add STup2 and RTup2 and their eliminators ; this solves the traversal problem by making it expicit and correct by construction
    - add example for STup2
    - add static or dynamic assertion to MkInd to check that the referred value is written ; this guarantees the correctness of DeRefPtr
      every function argument must be fully written, every return value must be fully written
-}
