module LoCal

import Control.Function
import Decidable.Equality

public export
data Ty : Type where
  T0      : Ty
  Pair    : Ty -> Ty -> Ty   -- serial access only, fst then snd
  Either  : Ty -> Ty -> Ty
  I64     : Ty
  -- IDEA: Offset - region local ; Ptr - cross region
  Offset  : Ty -> Ty -- signed pointer offset value
  Ptr     : Ty -> Ty -- raw pointer ; no tag ; just the location data
  -- recursive type support
  Box     : String -> Lazy Ty -> Ty

public export
showTy : Ty -> String
showTy t = case t of
  T0          => "T0"
  Pair a b    => "Pair (\{showTy a}) (\{showTy b})"
  Either a b  => "Either (\{showTy a}) (\{showTy b})"
  I64         => "I64"
  Offset a    => "Offset (\{showTy a})"
  Ptr a       => "Ptr (\{showTy a})"
  Box n t     => "Box \{n}"

public export Show Ty  where show = showTy
public export Eq Ty    where a == b = showTy a == showTy b
public export DecEq Ty where decEq = decEq @{FromEq}

public export
getStaticSize : Ty -> Maybe Int
getStaticSize = \case
  T0    => Just 0
  I64   => pure 8
  Offset _ => pure 8
  Ptr _ => pure 8
  Pair a b => do
    sa <- getStaticSize a
    sb <- getStaticSize b
    pure (sa + sb)
  Either a b => do
    sa <- getStaticSize a
    sb <- getStaticSize b
    if sa == sb -- special case, when the left and right size matches and statically known
      then Just (1 + sa)
      else Nothing
  Box _ _ => Nothing

{-
  INSIGHT:
    control flow construct data
      if          -> + types
      basic block -> * types
    unconstrained recursion needs Box!!!
-}

{-
  REPRESENTATION:
    - no tag:   I64, Pair
    - has tag:  Either

  FUTURE WORK:
    - either should use only one bit tag
      + implement packing of multiple tags into a byte or multiple bytes
      + implement sub byte/word addressing but by tags and data
    - add alignment control to locations
-}


public export
data Region : Type where
  MkRegion : Int -> Region

export
Injective MkRegion where
  injective Refl = Refl

public export
DecEq Region where
  decEq (MkRegion x) (MkRegion y) = decEqCong $ decEq x y


public export
data Loc : (r : Region) -> Type where
  LocStart    : (t : Ty) -> (r : Region) -> Loc r
  LocAfter    : (t : Ty) -> Loc r -> Loc r
  LocAfterTag : String -> (t : Ty) -> Loc r -> Loc r -- statically known ; used for jump over the tag

{-
  mvp simplifications:
    - only pair and either ; product and sum type
    - only I64 interger primitive type

  Q: what about stack frames and stack based memory management?
  Q: what about returning values in registers?
  A: use special region for that, or use escape analysis on regions
-}

public export
data EndWitness = NoEW | EW -- TODO: index it with Loc

-- TODO: add linear arrows to guarantee that codegen happens for each expression exactly once
{-
  Q: is LoCal program pure and can it be interpreted through data dependencies only where dependecy is sequential due to neighboring locations?
     does the Exp's operations guarantee dependency serializability through the EW type constraints?

  TODO:
    - new backend for the CPS IR:
      + operations are generated by following theit locations from start to the end
      + each region is filled sequentially, but region's operation codegen can be interleaved
      why? because for the non CPS IR the codegen naturally followed the location order,
        i.e. for Tup2 first generated code for fst then for snd and Tup2 codegen happended strictly before fst and snd codegen, and that is not true for CPS
        see the following example where snd's MkI64 expression is the root where the codegen start:
            MkI64 102 $ \snd =>
            MkI64 101 $ \fst =>
            MkRTup2 fst snd $ \fst, snd, t => t

      Q: why is CPS good then?
      A: because: a) it avoids explosion b) traversal effect is tracked

      INSIGHT: the direct value style IR express location order directed codegen naturally, so it is better than the CPS IR version
-}

public export
data IntOp2 = Plus | Sub | Times | Quot | Rem

public export
data CmpOp = EQ | GE | GT | LE | LT | NE

public export
data Exp : (t : Ty) -> (loc : Loc r) -> (ew : EndWitness) -> (saved_ews : List Type) -> Type

public export
data Arg : (sig : List Type) -> Type where
  Arg0 : Arg []
  ArgN : {t : _} -> {r : _} -> {loc : Loc r} -> {ew : _} -> Exp t loc ew [] -> Arg s -> Arg (Exp t loc ew [] :: s)

data Exp where

  -- Q: when to introduce new regions? A: for intermediate values
  LetRegion : (Region -> Exp t loc ew ews) -> Exp t loc ew ews -- TODO: remove this op, or add an iterpretation layer that evaluates it
  LetRegionValue : {t_val : _} -> (r_val : Region) -> Exp t_val (LocStart t_val r_val) EW [] ->
                   (Exp t_val (LocStart t_val r_val) EW [] -> Exp a loc ew ews) -> Exp a loc ew ews

  -- to copy values cross region ; requires full traversal effect on the argument, so the end-witness should be available
  Copy : {loc_in : _} -> Exp t loc_in EW [] -> Exp t loc EW []

  -- boxing
  MkBox : {n : String} -> Exp t loc ew [] -> Exp (Box n t) loc ew []
  UnBox : Exp (Box _ t) loc ew [] -> Exp t loc ew []

  -- value shapes, ADT can be modeled with these

  -- MkPair is the only origin of the 'after' relation between locations
  MkPair : {a, b : Ty} -> {loc : _} ->
    let locFst = LocAfterTag "Pair" a loc in
    let locSnd = LocAfter b locFst in
    Exp a locFst EW [] -> Exp b locSnd EW [] -> Exp (Pair a b) loc EW []

  MkLeft  : {a, b : Ty} -> {loc : _} ->
    let locArg = LocAfterTag "Left" a loc in
    Exp a locArg EW [] -> Exp (Either a b) loc EW []

  MkRight : {a, b : Ty} -> {loc : _} ->
    let locArg = LocAfterTag "Right" b loc in
    Exp b locArg EW [] -> Exp (Either a b) loc EW []

  -- serial access pair
  {-
  CasePair : {r_tup : _} -> {a, b, c : Ty} -> {loc_tup : Loc r_tup} -> {ew_tup, ew : _} -> {loc : _} -> {ews : _} ->
              Exp (Pair a b) loc_tup ew_tup [] ->
              let locFst = LocAfterTag "Pair" a loc_tup in
              let locSnd = LocAfter b locFst in
              ( Exp a locFst NoEW [] ->
                -- gives access for snd
                (snd_fun : Exp a locFst EW [] -> Exp b locSnd ew_tup []) ->
                -- gives end-witness for Pair
                {tup_ew_fun : Exp b locSnd EW [] -> Exp (Pair a b) loc_tup EW []} ->
                Exp c loc ew ews
              ) -> Exp c loc ew ews
  -}
  -- instead of CasePair
  GetFst : {r_tup : _} -> {a, b : Ty} -> {loc_tup : Loc r_tup} -> {ew_tup : _} ->
              Exp (Pair a b) loc_tup ew_tup [] ->
              let locFst = LocAfterTag "Pair" a loc_tup in
              Exp a locFst NoEW []

  GetSnd : {r_tup : _} -> {a, b : Ty} -> {loc_tup : Loc r_tup} -> {ew_tup: _} ->
           Exp (Pair a b) loc_tup ew_tup [] ->
           let locFst = LocAfterTag "Pair" a loc_tup in
           let locSnd = LocAfter b locFst in
           Exp a locFst EW [] -> Exp b locSnd ew_tup []
  {-
  CaseEither : {r_scrut : _} -> {a, b, c : Ty} -> {loc_scrut : Loc r_scrut} -> {ew_scrut, ew : _} -> {loc : _} -> {ews : _} ->
               Exp (Either a b) loc_scrut ew_scrut [] ->
               let locL = LocAfterTag "Left"  a loc_scrut in
               let locR = LocAfterTag "Right" b loc_scrut in
               (Exp a locL ew_scrut [] -> {either_ew_fun : Exp a locL EW [] -> Exp (Either a b) loc_scrut EW []} -> Exp c loc ew ews) ->
               (Exp b locR ew_scrut [] -> {either_ew_fun : Exp b locR EW [] -> Exp (Either a b) loc_scrut EW []} -> Exp c loc ew ews) ->
               Exp c loc ew ews
  -}
  NewCaseEither : {r_scrut : _} -> {a, b, c : Ty} -> {loc_scrut : Loc r_scrut} -> {ew_scrut, ew : _} -> {loc : _} -> {ews : _} ->
               Exp (Either a b) loc_scrut ew_scrut [] ->
               let locL = LocAfterTag "Left"  a loc_scrut in
               let locR = LocAfterTag "Right" b loc_scrut in
               (Exp a locL ew_scrut [] -> Exp c loc ew ews) ->
               (Exp b locR ew_scrut [] -> Exp c loc ew ews) ->
               Exp c loc ew ews

  -- IDEA: store end-witnesses as an index in Exp
  AddEW : Exp t1 loc1 EW [] -> Exp t2 loc2 ew2 ews2 -> Exp t2 loc2 ew2 (Exp t1 loc1 EW [] :: ews2)

  FunAppNew : {res : _} -> {r_res : _} -> {loc_res : Loc r_res} ->
           String ->
           (fun_def : Arg exps_in -> Exp res loc_res EW fun_ews) ->
           (fun_args : Arg exps_in) ->
           (Arg fun_ews -> Exp res loc_res EW [] -> Exp c loc ew ews) ->
           Exp c loc ew ews

  -- indirection, within same region
  MkOffset    : {ew_in : _} -> {r : _} -> {loc, loc_in : Loc r} -> Exp x loc_in ew_in [] -> Exp (Offset x) loc EW []
  DeRefOffset : {x : _} -> {ew_in : _} -> {r_in : _} -> {loc_in : Loc r_in} ->
                Exp (Offset x) loc_in ew_in [] -> ({r_val : _} -> Exp x (LocStart x r_val) NoEW [] -> Exp a loc ew ews) -> Exp a loc ew ews

  {-
    TODO:
      - add assertion to throw error on read before write situations, which can happen with forward pointers and dereference
      - create and example for this case
      Q: how does this interact with function calls?
  -}
  -- indirection, cross region
  MkPtr    : {ew_in : _} -> {r_in : _} -> {loc_in : Loc r_in} -> Exp x loc_in ew_in [] -> Exp (Ptr x) loc EW []
  DeRefPtr : {x : _} -> {ew_in : _} -> {r_in : _} -> {loc_in : Loc r_in} ->
             Exp (Ptr x) loc_in ew_in [] -> ({r_val : _} -> Exp x (LocStart x r_val) NoEW [] -> Exp a loc ew ews) -> Exp a loc ew ews

  -- primitive values
  MkT0  : Exp T0 loc EW []
  MkI64 : Int -> Exp I64 loc EW []

  -- I64 primops
  I64Op2  : IntOp2 -> {ew1, ew2 : _} -> {loc_in1, loc_in2 : _} -> Exp I64 loc_in1 ew1 [] -> Exp I64 loc_in2 ew2 [] -> Exp I64 loc EW []
  I64Cmp  : CmpOp  -> {ew1, ew2 : _} -> {loc_in1, loc_in2 : _} -> Exp I64 loc_in1 ew1 [] -> Exp I64 loc_in2 ew2 [] -> Exp (Either T0 T0) loc EW []

  I64Op2CE : IntOp2 -> Int -> {ew2 : _} -> {loc_in2 : _} -> Exp I64 loc_in2 ew2 [] -> Exp I64 loc EW []
  I64Op2EC : IntOp2 -> {ew1 : _} -> {loc_in1 : _} -> Exp I64 loc_in1 ew1 [] -> Int -> Exp I64 loc EW []
  I64CmpC  : CmpOp  -> Int -> {ew2 : _} -> {loc_in2 : _} -> Exp I64 loc_in2 ew2 [] -> Exp (Either T0 T0) loc EW []

  -- IO primops
  PrintI64 : {ew_in : _} -> {loc_in : _} -> Exp I64 loc_in ew_in [] -> (() -> Exp t loc ew ews) -> Exp t loc ew ews

  -- prints the buffer content at the location in hexadecimal
  PrintValue : {loc_in : _} -> Exp t_in loc_in EW [] -> (() -> Exp t loc ew ews) -> Exp t loc ew ews

  -- internal
  Var : Exp t loc ew sew
  --InheritEW : {r_in : _} -> {loc_in : Loc r_in} -> Exp a loc_in EW [] -> Exp b loc EW [] -- new version: PairEW, LeftEW, RightEW
  --AddLocAfter : {b : _} -> {locFst : _} -> Exp a locFst EW [] -> Exp b (LocAfter b locFst) ew [] -- new version: GetSnd

  -- new formulation
  --GetSnd : {b : _} -> {locFst : _} -> Exp a locFst EW [] -> Exp b (LocAfter b locFst) ew []

  -- instead of AddLocAfter

  -- temp stuff
  LetTick : Int -> Exp t loc ew sew -> Exp t loc ew sew


  -- end-witnesses

  -- TODO: rename to StaticEW
  StaticEW : {ew_in : _} -> {auto _ : Just size = getStaticSize t} -> Exp t loc ew_in [] -> Exp t loc EW []

  GenEW : Exp t loc ew_in [] -> Exp t loc EW []


  -- instead of InheritEW
  PairEW : {r_tup : _} -> {a, b : Ty} -> {loc_tup : Loc r_tup} -> {ew_tup : _} ->
           Exp (Pair a b) loc_tup ew_tup [] ->
           let locFst = LocAfterTag "Pair" a loc_tup in
           let locSnd = LocAfter b locFst in
           Exp b locSnd EW [] -> Exp (Pair a b) loc_tup EW []

  LeftEW : {r_scrut : _} -> {a, b : Ty} -> {loc_scrut : Loc r_scrut} ->
           Exp (Either a b) loc_scrut ew_scrut [] ->
           let locL = LocAfterTag "Left" a loc_scrut in
           Exp a locL EW [] -> Exp (Either a b) loc_scrut EW []

  RightEW : {r_scrut : _} -> {a, b : Ty} -> {loc_scrut : Loc r_scrut} ->
            Exp (Either a b) loc_scrut ew_scrut [] ->
            let locR = LocAfterTag "Right" b loc_scrut in
            Exp b locR EW [] -> Exp (Either a b) loc_scrut EW []

public export
data Program : Type where
  Main  : {res : Ty} -> Exp res (LocStart res (MkRegion (-1))) EW [] -> Program
