module LoCal

import Control.Function
import Decidable.Equality
import Data.Primitives.Interpolation

public export
data Ty : Type where
  T0      : Ty
  Pair    : Ty -> Ty -> Ty   -- serial access only, fst then snd
  Either  : Ty -> Ty -> Ty
  I64     : Ty
  -- IDEA: Offset - region local ; Ptr - cross region
  Offset  : Ty -> Ty -- signed pointer offset value
  Ptr     : Ty -> Ty -- raw pointer ; no tag ; just the location data
  -- recursive type support
  Box     : String -> Lazy Ty -> Ty

public export
showTy : Ty -> String
showTy t = case t of
  T0          => "T0"
  Pair a b    => "Pair (\{showTy a}) (\{showTy b})"
  Either a b  => "Either (\{showTy a}) (\{showTy b})"
  I64         => "I64"
  Offset a    => "Offset (\{showTy a})"
  Ptr a       => "Ptr (\{showTy a})"
  Box n t     => "Box \{n}"

public export Show Ty  where show = showTy
public export Eq Ty    where a == b = showTy a == showTy b
public export DecEq Ty where decEq = decEq @{FromEq}

public export
getStaticSize : Ty -> Maybe Int
getStaticSize = \case
  T0    => Just 0
  I64   => pure 8
  Offset _ => pure 8
  Ptr _ => pure 8
  Pair a b => do
    sa <- getStaticSize a
    sb <- getStaticSize b
    pure (sa + sb)
  Either a b => do
    sa <- getStaticSize a
    sb <- getStaticSize b
    if sa == sb -- special case, when the left and right size matches and statically known
      then Just (1 + sa)
      else Nothing
  Box _ _ => Nothing

public export
isStaticSize : Ty -> Bool
isStaticSize t = case getStaticSize t of
  Nothing => False
  Just{}  => True

{-
  INSIGHT:
    control flow construct data
      if          -> + types
      basic block -> * types
    unconstrained recursion needs Box!!!
-}

{-
  REPRESENTATION:
    - no tag:   I64, Pair
    - has tag:  Either

  FUTURE WORK:
    - either should use only one bit tag
      + implement packing of multiple tags into a byte or multiple bytes
      + implement sub byte/word addressing but by tags and data
    - add alignment control to locations
-}


public export
data Region : Type where
  MkRegion    : Int -> Region
  MkArgRegion : String -> Nat -> Region

export
Injective MkRegion where
  injective Refl = Refl

export
{x : _} -> Injective (MkArgRegion x) where
  injective Refl = Refl

export
{y : _} -> Injective (`MkArgRegion` y) where
  injective Refl = Refl

export
Biinjective MkArgRegion where
  biinjective Refl = (Refl, Refl)

public export
Uninhabited (MkRegion _ = MkArgRegion _ _) where
  uninhabited Refl impossible

public export
Uninhabited (MkArgRegion _ _ = MkRegion _) where
  uninhabited Refl impossible

public export
DecEq Region where
  decEq (MkRegion x) (MkRegion y) = decEqCong $ decEq x y
  decEq (MkArgRegion n1 i1) (MkArgRegion n2 i2) = decEqCong2 (decEq n1 n2) (decEq i1 i2)
  decEq (MkRegion _) (MkArgRegion _ _) = No absurd
  decEq (MkArgRegion _ _) (MkRegion _) = No absurd

showRegion : Region -> String
showRegion (MkRegion i) = "MkRegion \{i}"
showRegion (MkArgRegion n i) = "MkArgRegion \{n} \{i}"

public export Show Region where show = showRegion

public export
data Loc : (r : Region) -> Type where
  LocStart    : (t : Ty) -> (r : Region) -> Loc r
  LocAfter    : (t : Ty) -> Loc r -> Loc r
  LocAfterTag : String -> (t : Ty) -> Loc r -> Loc r -- statically known ; used for jump over the tag

showLoc : Loc r -> String
showLoc loc = case loc of
  LocStart t r => "LocStart (\{show t}) (\{show r})"
  LocAfter t l => "LocAfter (\{show t})\n (\{showLoc l})"
  LocAfterTag s t l => "LocAfterTag \{s} (\{show t})\n (\{showLoc l})"

public export Show (Loc r) where show = showLoc
public export Eq (Loc r)    where a == b = showLoc a == showLoc b
public export DecEq (Loc r) where decEq = decEq @{FromEq}

{-
  mvp simplifications:
    - only pair and either ; product and sum type
    - only I64 interger primitive type

  Q: what about stack frames and stack based memory management?
  Q: what about returning values in registers?
  A: use special region for that, or use escape analysis on regions
-}

public export
data EndWitness = NoEW | EW -- TODO: index it with Loc

public export
Uninhabited (EW = NoEW) where
  uninhabited Refl impossible

public export
Uninhabited (NoEW = EW) where
  uninhabited Refl impossible

public export
DecEq EndWitness where
  decEq EW   EW   = Yes Refl
  decEq NoEW NoEW = Yes Refl
  decEq NoEW EW   = No absurd
  decEq EW   NoEW = No absurd

-- TODO: add linear arrows to guarantee that codegen happens for each expression exactly once
{-
  Q: is LoCal program pure and can it be interpreted through data dependencies only where dependecy is sequential due to neighboring locations?
     does the Exp's operations guarantee dependency serializability through the EW type constraints?

  TODO:
    - new backend for the CPS IR:
      + operations are generated by following theit locations from start to the end
      + each region is filled sequentially, but region's operation codegen can be interleaved
      why? because for the non CPS IR the codegen naturally followed the location order,
        i.e. for Tup2 first generated code for fst then for snd and Tup2 codegen happended strictly before fst and snd codegen, and that is not true for CPS
        see the following example where snd's MkI64 expression is the root where the codegen start:
            MkI64 102 $ \snd =>
            MkI64 101 $ \fst =>
            MkRTup2 fst snd $ \fst, snd, t => t

      Q: why is CPS good then?
      A: because: a) it avoids explosion b) traversal effect is tracked

      INSIGHT: the direct value style IR express location order directed codegen naturally, so it is better than the CPS IR version
-}

public export
data IntOp2 = Plus | Sub | Times | Quot | Rem

public export
data CmpOp = EQ | GE | GT | LE | LT | NE

public export
data RWMode = R | W

public export
data Exp : (rw : RWMode) -> (t : Ty) -> (loc : Loc r) -> (ew : EndWitness) -> (saved_ews : List Type) -> Type

public export
data Arg : {fun : String} -> {n : Nat} -> (sig : List Type) -> Type where
  Arg0 : {fun : _} -> Arg {fun} {n=0} []
  ArgN : {fun : _} -> {n : _} -> {t : _} -> {r_arg : _} -> {loc_arg : Loc r_arg} -> {ew : _} -> Exp R t loc_arg ew [] -> Arg {fun} {n} s ->
         Arg {fun} {n=S n} (Exp R t (LocStart t $ MkArgRegion fun n) ew [] :: s)

data Exp where

  -- Q: when to introduce new regions? A: for intermediate values
  LetRegion : (Region -> Exp rw t loc ew ews) -> Exp rw t loc ew ews -- TODO: remove this op, or add an iterpretation layer that evaluates it
  LetRegionValue : {t_val : _} -> (r_val : Region) -> Exp W t_val (LocStart t_val r_val) EW [] ->
                   (Exp R t_val (LocStart t_val r_val) EW [] -> Exp rw a loc ew ews) -> Exp rw a loc ew ews

  -- to copy values cross region ; requires full traversal effect on the argument, so the end-witness should be available
  Copy : {r_in : _} -> {loc_in : Loc r_in} -> Exp R t loc_in EW [] -> Exp W t loc EW []

  -- boxing
  MkBox : {t : Ty} -> {n : String} -> Exp rw t loc ew [] -> Exp rw (Box n $ Delay t) loc ew []
  UnBox : {t : Ty} -> {n : String} -> Exp rw (Box n $ Delay t) loc ew [] -> Exp rw t loc ew []

  -- value shapes, ADT can be modeled with these

  -- MkPair is the only origin of the 'after' relation between locations
  MkPair : {a, b : Ty} -> {loc : _} ->
    let locFst = LocAfterTag "Pair" a loc in
    let locSnd = LocAfter b locFst in
    Exp W a locFst EW [] -> Exp W b locSnd EW [] -> Exp W (Pair a b) loc EW []

  MkLeft  : {a, b : Ty} -> {loc : _} ->
    let locArg = LocAfterTag "Left" a loc in
    Exp W a locArg EW [] -> Exp W (Either a b) loc EW []

  MkRight : {a, b : Ty} -> {loc : _} ->
    let locArg = LocAfterTag "Right" b loc in
    Exp W b locArg EW [] -> Exp W (Either a b) loc EW []

  -- serial access pair
  GetFst : {r_tup : _} -> {a, b : Ty} -> {loc_tup : Loc r_tup} -> {ew_tup : _} ->
              Exp R (Pair a b) loc_tup ew_tup [] ->
              let locFst = LocAfterTag "Pair" a loc_tup in
              Exp R a locFst NoEW []

  GetSnd : {r_tup : _} -> {a, b : Ty} -> {loc_tup : Loc r_tup} -> {ew_tup: _} ->
           Exp R (Pair a b) loc_tup ew_tup [] ->
           let locFst = LocAfterTag "Pair" a loc_tup in
           let locSnd = LocAfter b locFst in
           Exp R a locFst EW [] -> Exp R b locSnd ew_tup []

  CaseEither : {rw : _} -> {r_scrut : _} -> {a, b, c : Ty} -> {loc_scrut : Loc r_scrut} -> {ew_scrut, ew : _} -> {loc : _} -> {ews : _} ->
               Exp R (Either a b) loc_scrut ew_scrut [] ->
               let locL = LocAfterTag "Left"  a loc_scrut in
               let locR = LocAfterTag "Right" b loc_scrut in
               (Exp R a locL ew_scrut [] -> Exp rw c loc ew ews) ->
               (Exp R b locR ew_scrut [] -> Exp rw c loc ew ews) ->
               Exp rw c loc ew ews

  -- IDEA: store end-witnesses as an index in Exp
  AddEW : Exp rw1 t1 loc1 EW [] -> Exp rw2 t2 loc2 ew2 ews2 -> Exp rw2 t2 loc2 ew2 (Exp rw1 t1 loc1 EW [] :: ews2)
  GetEWS : Exp _ _ _ _ fun_ews -> (Arg fun_ews -> Exp rw c loc ew ews) -> Exp rw c loc ew ews

  FunAppDef : {fun_ews : _} -> {res : _} -> {r_res : _} -> {loc_res : Loc r_res} ->
           (fun : String) ->
           (fun_def  : Arg {fun} {n} exps_in  -> Exp W res loc_res EW fun_ews) ->
           (fun_args : Arg {fun} {n} exps_in) -> Exp W res loc_res EW fun_ews

  FunApp : {fun_ews : _} -> {res : _} -> {r_res : _} -> {loc_res : Loc r_res} ->
           String ->
           (fun_args : Arg exps_in) -> Exp W res loc_res EW fun_ews

  -- indirection, within same region
  MkOffset    : {ew_in : _} -> {r : _} -> {loc, loc_in : Loc r} -> Exp W x loc_in ew_in [] -> Exp W (Offset x) loc EW []
  DeRefOffset : {x : _} -> {ew_in : _} -> {r_in : _} -> {loc_in : Loc r_in} ->
                Exp R (Offset x) loc_in ew_in [] -> ({r_val : _} -> Exp R x (LocStart x r_val) NoEW [] -> Exp rw a loc ew ews) -> Exp rw a loc ew ews

  {-
    TODO:
      - add assertion to throw error on read before write situations, which can happen with forward pointers and dereference
      - create and example for this case
      Q: how does this interact with function calls?
  -}
  -- indirection, cross region
  MkPtr    : {ew_in : _} -> {r_in : _} -> {loc_in : Loc r_in} -> Exp rw_n x loc_in ew_in [] -> Exp W (Ptr x) loc EW []
  DeRefPtr : {x : _} -> {ew_in : _} -> {r_in : _} -> {loc_in : Loc r_in} ->
             Exp R (Ptr x) loc_in ew_in [] -> ({r_val : _} -> Exp R x (LocStart x r_val) NoEW [] -> Exp rw a loc ew ews) -> Exp rw a loc ew ews

  -- primitive values
  MkT0  : Exp W T0 loc EW []
  MkI64 : Int -> Exp W I64 loc EW []

  -- I64 primops
  I64Op2  : IntOp2 -> {ew1, ew2 : _} -> {r_in1, r_in2 : _} -> {loc_in1 : Loc r_in1} -> {loc_in2 : Loc r_in2} -> Exp R I64 loc_in1 ew1 [] -> Exp R I64 loc_in2 ew2 [] -> Exp W I64 loc EW []
  I64Cmp  : CmpOp  -> {ew1, ew2 : _} -> {r_in1, r_in2 : _} -> {loc_in1 : Loc r_in1} -> {loc_in2 : Loc r_in2} -> Exp R I64 loc_in1 ew1 [] -> Exp R I64 loc_in2 ew2 [] -> Exp W (Either T0 T0) loc EW []

  -- IO primops
  PrintI64 : {ew_in : _} -> {r_in : _} -> {loc_in : Loc r_in} -> Exp R I64 loc_in ew_in [] -> (() -> Exp rw t loc ew ews) -> Exp rw t loc ew ews

  -- prints the buffer content at the location in hexadecimal
  PrintValue : {t_in : _} -> {r_in : _} -> {loc_in : Loc r_in} -> Exp R t_in loc_in EW [] -> (() -> Exp rw t loc ew ews) -> Exp rw t loc ew ews

  -- internal
  Var : Exp rw t loc ew sew

  -- end-witnesses
  StaticEW : {ew_in : _} -> {auto prf : True = isStaticSize t} -> Exp R t loc ew_in [] -> Exp R t loc EW []

  GenEW : {t : _} -> {r : _} -> {loc : Loc r} -> {ew_in : _} -> Exp R t loc ew_in [] -> Exp R t loc EW []

  PairEW : {r_tup : _} -> {a, b : Ty} -> {loc_tup : Loc r_tup} -> {ew_tup : _} ->
           Exp R (Pair a b) loc_tup ew_tup [] ->
           let locFst = LocAfterTag "Pair" a loc_tup in
           let locSnd = LocAfter b locFst in
           Exp R b locSnd EW [] -> Exp R (Pair a b) loc_tup EW []

  LeftEW : {ew_scrut : _} -> {r_scrut : _} -> {a, b : Ty} -> {loc_scrut : Loc r_scrut} ->
           Exp R (Either a b) loc_scrut ew_scrut [] ->
           let locL = LocAfterTag "Left" a loc_scrut in
           Exp R a locL EW [] -> Exp R (Either a b) loc_scrut EW []

  RightEW : {ew_scrut : _} -> {r_scrut : _} -> {a, b : Ty} -> {loc_scrut : Loc r_scrut} ->
            Exp R (Either a b) loc_scrut ew_scrut [] ->
            let locR = LocAfterTag "Right" b loc_scrut in
            Exp R b locR EW [] -> Exp R (Either a b) loc_scrut EW []

public export
data Program : Type where
  Main  : {res : Ty} -> Exp W res (LocStart res (MkRegion (-1))) EW [] -> Program

public export
showLoExpTag : Exp rw t loc ew ews -> String
showLoExpTag = \case
  LetRegion{} => "LetRegion"
  AddEW{}     => "AddEW"
  GetEWS{}    => "GetEWS"
  LetRegionValue{} => "LetRegionValue"
  Copy{}      => "Copy"
  MkBox{}     => "MkBox"
  UnBox{}     => "UnBox"
  MkPair{}    => "MkPair"
  MkLeft{}    => "MkLeft"
  MkRight{}   => "MkRight"
  GetFst{}    => "GetFst"
  GetSnd{}    => "GetSnd"
  CaseEither{} => "CaseEither"
  FunAppDef{} => "FunAppDef"
  FunApp{}    => "FunApp"
  MkT0{}      => "MkT0"
  MkI64{}     => "MkI64"
  I64Op2{}    => "I64Op2"
  I64Cmp{}    => "I64Cmp"
  PrintI64{}  => "PrintI64"
  PrintValue{}  => "PrintValue"
  Var{}       => "Var"
  StaticEW{}  => "StaticEW"
  GenEW{}     => "GenEW"
  _ => assert_total $ idris_crash "showLoExpTag - TODO"
